export class CountryList {

  countryLists = [
    { value:'Afganistan', display:'Afghanistan'},
    { value:'Albania', display:'Albania'},
    { value:'Algeria', display:'Algeria'},
    { value:'American Samoa', display:'American Samoa'},
    { value:'Andorra', display:'Andorra'},
    { value:'Angola', display:'Angola'},
    { value:'Anguilla', display:'Anguilla'},
    { value:'Antigua & Barbuda', display:'Antigua & Barbuda'},
    { value:'Argentina', display:'Argentina'},
    { value:'Armenia', display:'Armenia'},
    { value:'Aruba', display:'Aruba'},
    { value:'Australia', display:'Australia'},
    { value:'Austria', display:'Austria'},
    { value:'Azerbaijan', display:'Azerbaijan'},
    { value:'Bahamas', display:'Bahamas'},
    { value:'Bahrain', display:'Bahrain'},
    { value:'Bangladesh', display:'Bangladesh'},
    { value:'Barbados', display:'Barbados'},
    { value:'Belarus', display:'Belarus'},
    { value:'Belgium', display:'Belgium'},
    { value:'Belize', display:'Belize'},
    { value:'Benin', display:'Benin'},
    { value:'Bermuda', display:'Bermuda'},
    { value:'Bhutan', display:'Bhutan'},
    { value:'Bolivia', display:'Bolivia'},
    { value:'Bonaire', display:'Bonaire'},
    { value:'Bosnia & Herzegovina', display:'Bosnia & Herzegovina'},
    { value:'Botswana', display:'Botswana'},
    { value:'Brazil', display:'Brazil'},
    { value:'British Indian Ocean Ter', display:'British Indian Ocean Ter'},
    { value:'Brunei', display:'Brunei'},
    { value:'Bulgaria', display:'Bulgaria'},
    { value:'Burkina Faso', display:'Burkina Faso'},
    { value:'Burundi', display:'Burundi'},
    { value:'Cambodia', display:'Cambodia'},
    { value:'Cameroon', display:'Cameroon'},
    { value:'Canada', display:'Canada'},
    { value:'Canary Islands', display:'Canary Islands'},
    { value:'Cape Verde', display:'Cape Verde'},
    { value:'Cayman Islands', display:'Cayman Islands'},
    { value:'Central African Republic', display:'Central African Republic'},
    { value:'Chad', display:'Chad'},
    { value:'Channel Islands', display:'Channel Islands'},
    { value:'Chile', display:'Chile'},
    { value:'China', display:'China'},
    { value:'Christmas Island', display:'Christmas Island'},
    { value:'Cocos Island', display:'Cocos Island'},
    { value:'Colombia', display:'Colombia'},
    { value:'Comoros', display:'Comoros'},
    { value:'Congo', display:'Congo'},
    { value:'Cook Islands', display:'Cook Islands'},
    { value:'Costa Rica', display:'Costa Rica'},
    { value:'Cote DIvoire', display:'Cote DIvoire'},
    { value:'Croatia', display:'Croatia'},
    { value:'Cuba', display:'Cuba'},
    { value:'Curaco', display:'Curacao'},
    { value:'Cyprus', display:'Cyprus'},
    { value:'Czech Republic', display:'Czech Republic'},
    { value:'Denmark', display:'Denmark'},
    { value:'Djibouti', display:'Djibouti'},
    { value:'Dominica', display:'Dominica'},
    { value:'Dominican Republic', display:'Dominican Republic'},
    { value:'East Timor', display:'East Timor'},
    { value:'Ecuador', display:'Ecuador'},
    { value:'Egypt', display:'Egypt'},
    { value:'El Salvador', display:'El Salvador'},
    { value:'Equatorial Guinea', display:'Equatorial Guinea'},
    { value:'Eritrea', display:'Eritrea'},
    { value:'Estonia', display:'Estonia'},
    { value:'Ethiopia', display:'Ethiopia'},
    { value:'Falkland Islands', display:'Falkland Islands'},
    { value:'Faroe Islands', display:'Faroe Islands'},
    { value:'Fiji', display:'Fiji'},
    { value:'Finland', display:'Finland'},
    { value:'France', display:'France'},
    { value:'French Guiana', display:'French Guiana'},
    { value:'French Polynesia', display:'French Polynesia'},
    { value:'French Southern Ter', display:'French Southern Ter'},
    { value:'Gabon', display:'Gabon'},
    { value:'Gambia', display:'Gambia'},
    { value:'Georgia', display:'Georgia'},
    { value:'Germany', display:'Germany'},
    { value:'Ghana', display:'Ghana'},
    { value:'Gibraltar', display:'Gibraltar'},
    { value:'Great Britain', display:'Great Britain'},
    { value:'Greece', display:'Greece'},
    { value:'Greenland', display:'Greenland'},
    { value:'Grenada', display:'Grenada'},
    { value:'Guadeloupe', display:'Guadeloupe'},
    { value:'Guam', display:'Guam'},
    { value:'Guatemala', display:'Guatemala'},
    { value:'Guinea', display:'Guinea'},
    { value:'Guyana', display:'Guyana'},
    { value:'Haiti', display:'Haiti'},
    { value:'Hawaii', display:'Hawaii'},
    { value:'Honduras', display:'Honduras'},
    { value:'Hong Kong', display:'Hong Kong'},
    { value:'Hungary', display:'Hungary'},
    { value:'Iceland', display:'Iceland'},
    { value:'Indonesia', display:'Indonesia'},
    { value:'India', display:'India'},
    { value:'Iran', display:'Iran'},
    { value:'Iraq', display:'Iraq'},
    { value:'Ireland', display:'Ireland'},
    { value:'Isle of Man', display:'Isle of Man'},
    { value:'Israel', display:'Israel'},
    { value:'Italy', display:'Italy'},
    { value:'Jamaica', display:'Jamaica'},
    { value:'Japan', display:'Japan'},
    { value:'Jordan', display:'Jordan'},
    { value:'Kazakhstan', display:'Kazakhstan'},
    { value:'Kenya', display:'Kenya'},
    { value:'Kiribati', display:'Kiribati'},
    { value:'Korea North', display:'Korea North'},
    { value:'Korea Sout', display:'Korea South'},
    { value:'Kuwait', display:'Kuwait'},
    { value:'Kyrgyzstan', display:'Kyrgyzstan'},
    { value:'Laos', display:'Laos'},
    { value:'Latvia', display:'Latvia'},
    { value:'Lebanon', display:'Lebanon'},
    { value:'Lesotho', display:'Lesotho'},
    { value:'Liberia', display:'Liberia'},
    { value:'Libya', display:'Libya'},
    { value:'Liechtenstein', display:'Liechtenstein'},
    { value:'Lithuania', display:'Lithuania'},
    { value:'Luxembourg', display:'Luxembourg'},
    { value:'Macau', display:'Macau'},
    { value:'Macedonia', display:'Macedonia'},
    { value:'Madagascar', display:'Madagascar'},
    { value:'Malaysia', display:'Malaysia'},
    { value:'Malawi', display:'Malawi'},
    { value:'Maldives', display:'Maldives'},
    { value:'Mali', display:'Mali'},
    { value:'Malta', display:'Malta'},
    { value:'Marshall Islands', display:'Marshall Islands'},
    { value:'Martinique', display:'Martinique'},
    { value:'Mauritania', display:'Mauritania'},
    { value:'Mauritius', display:'Mauritius'},
    { value:'Mayotte', display:'Mayotte'},
    { value:'Mexico', display:'Mexico'},
    { value:'Midway Islands', display:'Midway Islands'},
    { value:'Moldova', display:'Moldova'},
    { value:'Monaco', display:'Monaco'},
    { value:'Mongolia', display:'Mongolia'},
    { value:'Montserrat', display:'Montserrat'},
    { value:'Morocco', display:'Morocco'},
    { value:'Mozambique', display:'Mozambique'},
    { value:'Myanmar', display:'Myanmar'},
    { value:'Nambia', display:'Nambia'},
    { value:'Nauru', display:'Nauru'},
    { value:'Nepal', display:'Nepal'},
    { value:'Netherland Antilles', display:'Netherland Antilles'},
    { value:'Netherlands', display:'Netherlands (Holland)'},
    { value:'Nevis', display:'Nevis'},
    { value:'New Caledonia', display:'New Caledonia'},
    { value:'New Zealand', display:'New Zealand'},
    { value:'Nicaragua', display:'Nicaragua'},
    { value:'Niger', display:'Niger'},
    { value:'Nigeria', display:'Nigeria'},
    { value:'Niue', display:'Niue'},
    { value:'Norfolk Island', display:'Norfolk Island'},
    { value:'Norway', display:'Norway'},
    { value:'Oman', display:'Oman'},
    { value:'Pakistan', display:'Pakistan'},
    { value:'Palau Island', display:'Palau Island'},
    { value:'Palestine', display:'Palestine'},
    { value:'Panama', display:'Panama'},
    { value:'Papua New Guinea', display:'Papua New Guinea'},
    { value:'Paraguay', display:'Paraguay'},
    { value:'Peru', display:'Peru'},
    { value:'Phillipines', display:'Philippines'},
    { value:'Pitcairn Island', display:'Pitcairn Island'},
    { value:'Poland', display:'Poland'},
    { value:'Portugal', display:'Portugal'},
    { value:'Puerto Rico', display:'Puerto Rico'},
    { value:'Qatar', display:'Qatar'},
    { value:'Republic of Montenegro', display:'Republic of Montenegro'},
    { value:'Republic of Serbia', display:'Republic of Serbia'},
    { value:'Reunion', display:'Reunion'},
    { value:'Romania', display:'Romania'},
    { value:'Russia', display:'Russia'},
    { value:'Rwanda', display:'Rwanda'},
    { value:'St Barthelemy', display:'St Barthelemy'},
    { value:'St Eustatius', display:'St Eustatius'},
    { value:'St Helena', display:'St Helena'},
    { value:'St Kitts-Nevis', display:'St Kitts-Nevis'},
    { value:'St Lucia', display:'St Lucia'},
    { value:'St Maarten', display:'St Maarten'},
    { value:'St Pierre & Miquelon', display:'St Pierre & Miquelon'},
    { value:'St Vincent & Grenadines', display:'St Vincent & Grenadines'},
    { value:'Saipan', display:'Saipan'},
    { value:'Samoa', display:'Samoa'},
    { value:'Samoa American', display:'Samoa American'},
    { value:'San Marino', display:'San Marino'},
    { value:'Sao Tome & Principe', display:'Sao Tome & Principe'},
    { value:'Saudi Arabia', display:'Saudi Arabia'},
    { value:'Senegal', display:'Senegal'},
    { value:'Seychelles', display:'Seychelles'},
    { value:'Sierra Leone', display:'Sierra Leone'},
    { value:'Singapore', display:'Singapore'},
    { value:'Slovakia', display:'Slovakia'},
    { value:'Slovenia', display:'Slovenia'},
    { value:'Solomon Islands', display:'Solomon Islands'},
    { value:'Somalia', display:'Somalia'},
    { value:'South Africa', display:'South Africa'},
    { value:'Spain', display:'Spain'},
    { value:'Sri Lanka', display:'Sri Lanka'},
    { value:'Sudan', display:'Sudan'},
    { value:'Suriname', display:'Suriname'},
    { value:'Swaziland', display:'Swaziland'},
    { value:'Sweden', display:'Sweden'},
    { value:'Switzerland', display:'Switzerland'},
    { value:'Syria', display:'Syria'},
    { value:'Tahiti', display:'Tahiti'},
    { value:'Taiwan', display:'Taiwan'},
    { value:'Tajikistan', display:'Tajikistan'},
    { value:'Tanzania', display:'Tanzania'},
    { value:'Thailand', display:'Thailand'},
    { value:'Togo', display:'Togo'},
    { value:'Tokelau', display:'Tokelau'},
    { value:'Tonga', display:'Tonga'},
    { value:'Trinidad & Tobago', display:'Trinidad & Tobago'},
    { value:'Tunisia', display:'Tunisia'},
    { value:'Turkey', display:'Turkey'},
    { value:'Turkmenistan', display:'Turkmenistan'},
    { value:'Turks & Caicos Is', display:'Turks & Caicos Is'},
    { value:'Tuvalu', display:'Tuvalu'},
    { value:'Uganda', display:'Uganda'},
    { value:'United Kingdom', display:'United Kingdom'},
    { value:'Ukraine', display:'Ukraine'},
    { value:'United Arab Emirates', display:'United Arab Emirates'},
    { value:'United States of America', display:'United States of America'},
    { value:'Uraguay', display:'Uruguay'},
    { value:'Uzbekistan', display:'Uzbekistan'},
    { value:'Vanuatu', display:'Vanuatu'},
    { value:'Vatican City State', display:'Vatican City State'},
    { value:'Venezuela', display:'Venezuela'},
    { value:'Vietnam', display:'Vietnam'},
    { value:'Virgin Islands (Brit)', display:'Virgin Islands (Brit)'},
    { value:'Virgin Islands (USA)', display:'Virgin Islands (USA)'},
    { value:'Wake Island', display:'Wake Island'},
    { value:'Wallis & Futana Is', display:'Wallis & Futana Is'},
    { value:'Yemen', display:'Yemen'},
    { value:'Zaire', display:'Zaire'},
    { value:'Zambia', display:'Zambia'},
    { value:'Zimbabwe', display:'Zimbabwe'}
    ]

}
